---

- name: create project for devspaces operator
  k8s:
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: devspaces

- name: Create operator subscription for Devspaces
  kubernetes.core.k8s:
    merge_type:
    - merge
    definition: "{{ lookup('file', 'devspaces_subscription.yaml' ) }}"
  retries: 10
  delay: 30

- name: Create Devspaces Operator Group
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'devspaces-op-group.yml') | from_yaml }}"
  retries: 10
  delay: 5
  register: ds_op_config_result
  until: ds_op_config_result is not failed

- name: wait for the status of the Devspaces subscription to not be empty
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: devspaces
    namespace: devspaces
  register: devspaces_subscription_out
  until:
    - devspaces_subscription_out is defined
    - devspaces_subscription_out.resources is defined
    - devspaces_subscription_out.resources[0] is defined
    - devspaces_subscription_out.resources[0].status is defined
    - devspaces_subscription_out.resources[0].status.installplan is defined
  retries: 30
  delay: 20

- name: patch the installplan to approve it
  k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      metadata:
        namespace: devspaces
        name: "{{ devspaces_subscription_out.resources[0].status.installplan.name }}"
      spec:
        approved: true

- name: Wait for Devspaces CRD
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: devworkspaces.workspace.devfile.io
  register: r_devspaces_crd
  retries: 200
  delay: 10
  until: r_devspaces_crd.resources | list | length == 1

- name: Create CheCluster for Dev Spaces Namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'che-cluster-ns.yml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_che_result
  until: git_che_result is not failed

- name: Create CheCluster for Dev Spaces
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'che-cluster.yml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_che_result
  until: git_che_result is not failed
