---
# Implement your Post Workload deployment tasks here
# --------------------------------------------------

# Remove deployer-notification
- name: Remove consolenotifications deployer-notification
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConsoleNotification
    namespace: openshift-console
    name: deployer-notification

- name: Remove consolenotifications deployer-ibm-quarkus-status-banner
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConsoleNotification
    namespace: openshift-console
    name: deployer-ibm-quarkus-status-banner

- name: create serviceaccount deployer-cleanup-sa
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: ServiceAccount
    definition:
      metadata:
        name: deployer-cleanup-sa
        namespace: openshift-console

- name: create clusterrole deployer-cleanup-role
  kubernetes.core.k8s:
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    definition:
      metadata:
        name: deployer-cleanup-role
      rules:
      - apiGroups: ["console.openshift.io"]
        resources: ["*"]
        verbs: ["delete", "list", "get", "watch"]

- name: create clusterrolebinding deployer-cleanup-rbac
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: deployer-cleanup-rbac
    definition:
      subjects:
      - kind: ServiceAccount
        name: deployer-cleanup-sa
        namespace: openshift-console
      roleRef:
        kind: ClusterRole
        name: deployer-cleanup-role
        apiGroup: rbac.authorization.k8s.io

- name: create job deployer-cleanup-job
  kubernetes.core.k8s:
    api_version: batch/v1
    kind: Job
    name: deployer-cleanup-job
    namespace: openshift-console
    definition:
      spec:
        completions: 9
        activeDeadlineSeconds: 9900
        backoffLimit: 3
        template:
          spec:
            serviceAccountName: deployer-cleanup-sa
            restartPolicy: Never
            containers:
            - name: deployer-cleanup-run
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c"]
              args: ["until kubectl get consolenotification deployer-ibm-quarkus-status-banner ; do echo 'Waiting for consolenotification/deployer-ibm-quarkus-status-banner to return again...'; sleep 10; done; echo 'STATUS: READY'; kubectl delete consolenotification deployer-ibm-quarkus-status-banner"]

# Remove kube:admin login option
- name: Final Step - Removing kube-admin account
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: kube-system
    name: kubeadmin

# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Workload tasks completed successfully."
  when:
    - not silent | bool
    - not workload_shared_deployment | default(false) | bool

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: Post_workload tasks complete
  ansible.builtin.debug:
    msg: "Post-Software checks completed successfully"
  when:
    - not silent | bool
    - workload_shared_deployment | default(false) | bool
