apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: devspaces
  annotations:
    che.eclipse.org/checluster-defaults-cleanup: '{"spec.components.pluginRegistry.openVSXURL":"true"}'
spec:
  devEnvironments:
    defaultNamespace:
      autoProvision: true
      template: devspaces-<username>
    storage:
      pvcStrategy: per-user
    secondsOfInactivityBeforeIdling: -1
    defaultEditor: che-incubator/che-code/latest
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    disableContainerBuildCapabilities: true
    startTimeoutSeconds: 600
  components:
    cheServer:
      debug: false
      logLevel: INFO
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: 'https://open-vsx.org'
    imagePuller:
      enable: true
      spec:
        images: >-
          quarkus-stack-3-27=quay.io/ibm/quarkus-workshop-devspace:ibm-3.27.1;
          che-gateway=registry.redhat.io/devspaces/traefik-rhel9@sha256:7bd1c5582082949142aead1db07b45d41840c58c14ddf18b062df45283e1a316;
          che-code-injector=registry.redhat.io/devspaces/code-rhel9@sha256:7b68bf06abf4f2b948d21ffa82401b44f26965b093e4875653344ae2b7fe46c8;
          project-clone=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:3f0619571d6fa2259796f837ebfd0eb0fa225054ac38ed0d144245cccce51515;
  gitServices: {}
  networking: {}
